### ISSUE TITLE
Unable to make to make an iron-image responsive if it is loaded asynchronously

### ISSUE THREAD

**Issue by mmazzarolo** [PolymerElements/iron-image#8] opened 2015-05-22 18:49 UTC
Hi, I've been suggested to post this as an issue.
I'm not able to make an iron-image responsive if it is loaded asynchronously (e.g. from an iron-ajax call)... the standard `<img>` tag works though.

Here's an example (the first image is an `<img>`, the second is an `<iron-image>`): http://jsbin.com/funigo/2/edit?html,output

**Comment by Mazzaaaaa** [comment] 2015-05-23 16:33
I just noticed that the problem arises even if the image is not loaded asynchronously.
It seems that the problem is setting w/h in percentage:
http://jsbin.com/qokibi/1/edit?html,output

Even setting the `sizing` attribute will not work because the size of the image is not fixed.
Am I missing something? Is `iron-image` supposed to work this way?

**Comment by benjaminboruff** [comment] 2015-06-18 15:12
+1
I don't think there is a polymer analog to bootstrap's class="img-responsive".

**Comment by kbwatts** [comment] 2015-07-02 05:27
+1

**Comment by sjuanman** [comment] 2015-09-09 11:15
+1 i've the same problem

**Comment by gedw99** [comment] 2015-10-24 08:41
in addition, in OSX Safari, the image does not show at all

**Comment by ronnyroeller** [comment] 2015-10-28 08:46
+1

**Comment by gedw99** [comment] 2015-10-28 10:17
As a work around, I was able to make the images response with flex layout and media queries.
Here it is running: http://www.berlininfusions.com/#!/products
It uses 3 different media queries for different screen sizes. They need some adjustment actually for working well on different mobile, but it demonstrates the approach i used.

```
<dom-module id="my-product">
    <template>
        <!-- Need for general styles shared between elements-->
        <style include="shared-styles"></style>
        <style is="custom-style">
            :host {
                display: block;
            }

            .container {
                @apply(--layout-horizontal);
                @apply(--layout-wrap);
            }

            .flexchild {
                @apply(--layout-flex);
            }
        </style>

        <div class="container">
            <div class="img-container">
                <iron-image class="img-sized img-gray" sizing="contain" src="/images/content/product.jpg"></iron-image>
            </div>
            <div class="flexchild">

                <h1>Product</h1>
                <p>Smokin’ Chilli Infused Vodka</p>
                <p>Blended Citruses & Pomegranate</p>
                <p>Sweetened by Agave</p>
                <p>Feel The Heat</p>
                <p>Taste The Flavor</p>
                <p>Sweet, Sour and Spicy</p>
                <p></p>
                <p>HØT, (red) handle with care! (flame imagine)</p>
                <p></p>
                <p>Pouring Instructions:</p>
                <p>Shake it like it’s hot, HØT best served cold.</p>
            </div>
        </div>

    </template>

    <script>
        Polymer({
            is: 'my-product'

        });
    </script>

</dom-module>

---

<!--
Shared styles for all elements
-->

<dom-module id="shared-styles">
    <template>
        <style>

            h1 {
                color: white;
                font-family: 'Playfair Display', sans-serif;
                font-size: 18px;
                font-weight: bold;
                padding-top: 0px;
                margin-top: 30px;
                -webkit-font-smoothing: antialiased;
                text-rendering: optimizeLegibility;
                
            }

            p {
                color: white;
                font-family: 'Montserrat', sans-serif;
                font-size: 10px;
                font-weight: normal;
                padding-top: 0px;
                margin-top: 0px;
                -webkit-font-smoothing: antialiased;
                text-rendering: optimizeLegibility;
            }

            a{

                color: #ffffff;
                text-underline-position: below;
            }

            .img-container {
                padding-right: 50px
            }

            .img-sized {
                width: 200px;
                height: 300px;
            }
            /* For Debugging - shows true size.
            .img-gray {
                background-color: lightgray;
            }
            */

            @media (min-width: 650px) {
                h1 {
                    font-size: 22px;
                }
                p {
                    font-size: 12px;
                }
                .img-sized {
                    width: 300px;
                    height: 450px;
                }
            }

            @media (min-width: 900px) {
                h1 {
                    font-size: 32px;
                }
                p {
                    font-size: 14px;
                }
                .img-sized {
                    width: 400px;
                    height: 600px;
                }
            }
        </style>
    </template>
</dom-module>

```

**Comment by bicknellr** [comment] 2015-11-19 01:19
Looks like #13 was actually dupe of this, so it got fixed by #28. Here's an updated version of the demo: http://jsbin.com/favisohixe/1/edit?html,output. Also, you'll need to pull in the [web components polyfill](https://github.com/webcomponents/webcomponentsjs) in most browsers for now.

**Closed by bicknellr** 2015-11-19 01:19 UTC
Labels: bug

**Comment by gedw99** [comment] 2015-11-19 11:31
@bicknellr 
Wondering about i as a developer should proceed with taking on new releases ?
I can either keep updating of the PSK (Polymer Starter Kit), or i can change my Bower just for that package that seems fixed.
There are allot of cross dependencies between Polymer packages, and so just pulling a single Bower package. 

Would be great to hear your thought so this.

**Comment by bicknellr** [comment] 2015-11-24 17:38
Hi @gedw99, I brought this up with @cdata recently and he made a good point: maintaining your project as if it were a fork of the starter kit is probably not the best idea. I don't think the starter kit is maintained with the assumption that you'll update it after grabbing an initial snapshot with which to start your project. Updating the individual packages as they come along will allow you to handle any breaking changes in smaller pieces as well. But, it's really up to your particular situation.

**Comment by gedw99** [comment] 2015-11-24 20:18
Thanks for the advice.
I will give it a try that way.
I guess each component is not dependent on the same version of polymer, but as I said worth trying it out
