### ISSUE TITLE
Applying border-radius with CSS no longer works

### ISSUE THREAD

**Issue by balloob** [PolymerElements/iron-image#67] opened 2016-02-07 19:26 UTC
Not sure if this was a supported feature to begin with, but since it used to work I thought I'll mention it.

Using `iron-image` v1.2.2, adding a `border-radius: 50%` via CSS no longer works. The images end up being square.
Before: ![screen shot 2016-02-07 at 11 23 45](https://cloud.githubusercontent.com/assets/1444314/12874687/4ce3b83e-cd8d-11e5-9b2a-61c3d1050954.png) and after: ![screen shot 2016-02-07 at 11 23 32](https://cloud.githubusercontent.com/assets/1444314/12874686/4cdeb9a6-cd8d-11e5-9c75-61395ca4a973.png)

**Comment by bicknellr** [comment] 2016-02-08 18:33
I'm going to close this a as a dupe of #65 (and reopen that one); could you put your browser info there?

**Closed by bicknellr** 2016-02-08 18:33 UTC
